apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: team-a
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_port
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_password
