apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-cluster-binding
subjects:
  - kind: ServiceAccount
    name: monitor-sa
    namespace: rbac-lab
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
