apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-containers
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-runAsNonRoot
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Job
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kyverno
          - trivy-system
    validate:
      message: "Containers must not run as root. Set securityContext.runAsNonRoot: true and runAsUser >= 1000."
      pattern:
        spec:
          containers:
          - securityContext:
              runAsNonRoot: true
              runAsUser: ">= 1000"